# Copyright (c) 2026 Mick Krippendorf <m.krippendorf+hornet@posteo.de>
# SPDX-License-Identifier: MIT

"""
Constructive possible-worlds semantics for Hornet.

STRUCTURE — Accessibility relations as Kleisli arrows:
    Worlds are Database instances (complete valuations under CWA).
    Accessibility relations are Kleisli arrows `Database → [Database]`,
    composed via `compose` (Kleisli composition over the powerset monad).

    Modal dimensions are ordered by refinement:
        epistemic ≼ deontic ≼ compliance

    - epistemic_relation:
        Restricts the current world by shadowing subsets of accessible facts,
        modeling bounded awareness (non-monotonic).

    - deontic_relation:
        Extends the current world by overlaying subsets of performed obligations,
        modeling partial conformity (monotonic).

    - compliance_relation:
        Kleisli composition `epistemic ∘ deontic` (applied left-to-right as
        restriction then extension). Produces the full accessibility space.
        The composition is non-monotonic overall due to the epistemic component.

COALGEBRAIC VIEW:
    Each accessibility relation is a coalgebra
        Database → P(Database)
    where P is the finite powerset functor. Modal operators quantify over
    the worlds generated by this coalgebra.

SEMANTICS — Box and diamond:
    □φ  =  neg(then(access_as_goal(R), neg(φ)))
    ◇φ  =  then(access_as_goal(R), φ)

KNOWN LIMITATION — Box operators are purely boolean:
    k, o, and deemed_known do not propagate variable bindings outward.
    Any unifications produced inside a box evaluation remain local and
    are discarded by the double-neg structure.
    Diamond operators (possibly_k, possibly_o) do propagate bindings.

VACUOUS TRUTH — empty accessibility:
    Prevented structurally: powerset([]) = [()], so there is always at
    least one accessible world — the current database. Box over an empty
    set of facts or obligations evaluates against the unmodified database
    rather than vacuously succeeding.

FRAMEWORK INTERFACE — predicates that domains must implement:
    accessible/3  — facts an agent could have known at time T
    obligation/3  — actions an agent was required to perform at time T
    performed/3   — actions an agent actually performed at time T
    knows/3       — facts an agent came to know at time T
"""

from __future__ import annotations

from dataclasses import dataclass
from itertools import chain, combinations
from typing import Callable, Iterable, Iterator, cast

from hornet.clauses import Database, Environment, Subst, predicate, resolve
from hornet.combinators import Goal, Step, amb_from_iterable, lift_ctx, neg, then
from hornet.symbols import (
    Action,
    Agent,
    Fact,
    KnownFact,
    Query,
    T,
    accessible,
    deemed_known,
    fail,
    k,
    knows,
    o,
    obligation,
    performed,
    possibly_k,
    possibly_o,
)
from hornet.terms import NonVariable, Term, const

type AccessRelation = Callable[[Database], list[Database]]


def powerset[E](iterable: Iterable[E]) -> Iterator[tuple[E, ...]]:
    s = list(iterable)
    return chain.from_iterable(combinations(s, r) for r in range(len(s) + 1))


def switch[Ctx, Env](v: Ctx) -> Goal[Ctx, Env]:
    return lift_ctx(const(v))


@dataclass(frozen=True, slots=True)
class access_as_goal:
    access: AccessRelation

    def __call__(self, db: Database, env: Environment) -> Step[Database, Environment]:
        return amb_from_iterable(tuple(switch(w) for w in self.access(db)))(db, env)


@dataclass(frozen=True, slots=True)
class compose:
    """Kleisli composition of accessibility relations."""

    f: AccessRelation
    g: AccessRelation

    def __call__(self, db: Database) -> list[Database]:
        return [w2 for w1 in self.f(db) for w2 in self.g(w1)]


@dataclass(frozen=True, slots=True)
class epistemic_relation:
    """
    Accessibility relation for epistemic worlds: all subsets of facts
    the agent could have received, modeling bounded awareness.
    """

    agent: Term
    t: Term

    def __call__(self, db: Database) -> list[Database]:
        facts: list[NonVariable] = [
            cast(NonVariable, s[KnownFact])
            for s in db.ask(accessible(self.agent, KnownFact, self.t))
        ]
        return [db.shadow(*[f.when(fail) for f in hidden]) for hidden in powerset(facts)]


@dataclass(frozen=True, slots=True)
class deontic_relation:
    """
    Accessibility relation for compliance worlds: all subsets of
    obligations the agent could have performed.
    """

    agent: Term
    t: Term

    def __call__(self, db: Database) -> list[Database]:
        obligations: list[NonVariable] = [
            cast(NonVariable, s[Action]) for s in db.ask(obligation(self.agent, Action, self.t))
        ]
        return [
            db.overlay(*[performed(self.agent, act, self.t) for act in subset])
            for subset in powerset(obligations)
        ]


@dataclass(frozen=True, slots=True)
class compliance_relation:
    agent: Term
    t: Term

    def __call__(self, db: Database) -> list[Database]:
        return compose(
            epistemic_relation(self.agent, self.t),
            deontic_relation(self.agent, self.t),
        )(db)


def box(access: AccessRelation, query: Goal[Database, Environment]) -> Goal[Database, Environment]:
    """□φ: φ holds in all accessible worlds."""
    return neg(then(access_as_goal(access), neg(query)))


def dia(access: AccessRelation, query: Goal[Database, Environment]) -> Goal[Database, Environment]:
    """◇φ: φ holds in some accessible world."""
    return then(access_as_goal(access), query)


def modal(db: Database) -> Database:
    child = db.new_child()

    @child.tell
    @predicate(k(Query, Agent, T))
    def _(db: Database, subst: Subst) -> Step[Database, Environment]:
        return box(
            epistemic_relation(subst[Agent], subst[T]),
            resolve(subst[Query]),
        )(db, subst.env)

    @child.tell
    @predicate(o(Query, Agent, T))
    def _(db: Database, subst: Subst) -> Step[Database, Environment]:
        return box(
            deontic_relation(subst[Agent], subst[T]),
            resolve(subst[Query]),
        )(db, subst.env)

    @child.tell
    @predicate(possibly_k(Query, Agent, T))
    def _(db: Database, subst: Subst) -> Step[Database, Environment]:
        return dia(
            epistemic_relation(subst[Agent], subst[T]),
            resolve(subst[Query]),
        )(db, subst.env)

    @child.tell
    @predicate(possibly_o(Query, Agent, T))
    def _(db: Database, subst: Subst) -> Step[Database, Environment]:
        return dia(
            deontic_relation(subst[Agent], subst[T]),
            resolve(subst[Query]),
        )(db, subst.env)

    @child.tell
    @predicate(deemed_known(Agent, Fact, T))
    def _(db: Database, subst: Subst) -> Step[Database, Environment]:
        return box(
            compliance_relation(subst[Agent], subst[T]),
            resolve(knows(subst[Agent], subst[Fact], subst[T])),
        )(db, subst.env)

    return child
