from hornet import database
from hornet.modalities import modal
from hornet.symbols import (
    T0,
    T1,
    TX,
    A,
    Action,
    Agent,
    Amount,
    D,
    Fact,
    Limit,
    R,
    Rpt,
    Rule,
    T,
    after,
    came_into_force,
    compliance_world,
    epistemic_world,
    greater,
    holds_role,
    kleisli,
    learned,
    let,
    necessarily,
    obligation,
    performed,
    report_contains,
    report_generated,
    review_report,
    reviewed,
    threshold,
    transaction,
    treated_as_known,
    uncertain_fact,
    violation,
)


def main() -> None:
    db = modal(database())

    db.tell(
        # ── Domain events ────────────────────────────────────────────────
        transaction('tx17', 'employee_e', 250_000, 1),
        report_generated('rep42', 'tx17', 2),
        # ── Normative acts ───────────────────────────────────────────────
        came_into_force('r1', 0),
        threshold('r1', 0, 100_000),
        holds_role('alice', 'cfo', 0),
        # ── Domain rules ─────────────────────────────────────────────────
        after(T0, T).when(greater(T0, T)),
        violation(TX, Rule).when(
            transaction(TX, A, Amount, T),
            threshold(Rule, T0, Limit),
            ~after(T0, T),
            let(D, Amount - Limit),
            greater(D, 0),
        ),
        report_contains(R, violation(TX, Rule)).when(
            report_generated(R, TX, T),
            violation(TX, Rule),
        ),
        learned(Agent, Fact, T).when(
            reviewed(Agent, R, T),
            report_contains(R, Fact),
        ),
        reviewed(Agent, Rpt, T).when(
            performed(Agent, review_report(Rpt), T),
        ),
        obligation(Agent, review_report(Rpt), T).when(
            holds_role(Agent, 'cfo', T0),
            ~after(T0, T),
            report_generated(Rpt, A, T1),
            ~after(T1, T),
        ),
        # What counts as epistemically uncertain for an agent at time T:
        # any report generated by T that the agent hasn't reviewed.
        uncertain_fact(Agent, report_contains(Rpt, Fact), T).when(
            report_generated(Rpt, A, T1),
            ~after(T1, T),
            report_contains(Rpt, Fact),
            ~performed(Agent, review_report(Rpt), T),
        ),
        # treated_as_known: necessarily, in all compliance worlds,
        # necessarily, in all epistemic worlds, the agent learned the fact.
        treated_as_known(Agent, Fact, T).when(
            necessarily(
                learned(Agent, Fact, T),
                kleisli(
                    epistemic_world(uncertain_fact(Agent, Fact, T), Agent, T),
                    compliance_world(obligation(Agent, Action, T), Agent, T),
                ),
            )
        ),
    )

    # ── Query ────────────────────────────────────────────────────────
    t_query = 2
    result = any(db.ask(treated_as_known('alice', violation('tx17', 'r1'), t_query)))
    print(f'treated_as_known(alice, violation(tx17, r1), {t_query}): {result}')


if __name__ == '__main__':
    main()
