# Copyright (c) 2013-2025 Mick Krippendorf <m.krippendorf+hornet@posteo.de>
# SPDX-License-Identifier: MIT

from hornet import DCGs, database
from hornet.clauses import Database
from hornet.symbols import E  # type: ignore[reportUnusedImport]
from hornet.symbols import S  # type: ignore[reportUnusedImport]
from hornet.symbols import (
    C,
    Case,
    D,
    F,
    Gender,
    Number,
    Trans,
    W,
    _,
    accusative,
    dative,
    det,
    equal,
    feminine,
    genitive,
    intransitive,
    masculine,
    neuter,
    nominative,
    noun,
    np,
    phrase,
    plural,
    s,
    singular,
    transitive,
    verb,
    vp,
)


def grammar(db: Database):
    db.tell(
        *DCGs(
            s.when(
                np(Number, nominative),
                vp(Number, nominative, intransitive),
            ),
            s.when(
                np(Number, Case),
                vp(Number, Case, transitive),
            ),
            np(plural, Case).when(
                noun(_, plural, Case),
            ),
            np(Number, Case).when(
                det(Gender, Number, Case),
                noun(Gender, Number, Case),
            ),
            vp(Number, nominative, intransitive).when(
                verb(Number, nominative, intransitive),
            ),
            vp(Number, accusative, intransitive).when(
                verb(Number, accusative, intransitive),
            ),
            vp(_, dative, transitive).when(
                verb(Number, nominative, transitive),
                np(Number, nominative),
            ),
            vp(Number, nominative, transitive).when(
                verb(Number, nominative, transitive),
                np(_, dative),
            ),
            vp(Number, nominative, transitive).when(
                verb(Number, accusative, transitive),
                np(_, accusative),
            ),
            det(masculine, singular, nominative).when(['der']),
            det(masculine, singular, genitive).when(['des']),
            det(masculine, singular, dative).when(['dem']),
            det(masculine, singular, accusative).when(['den']),
            det(masculine, plural, nominative).when(['die']),
            det(masculine, plural, genitive).when(['der']),
            det(masculine, plural, dative).when(['den']),
            det(masculine, plural, accusative).when(['die']),
            det(feminine, singular, nominative).when(['die']),
            det(feminine, singular, genitive).when(['der']),
            det(feminine, singular, dative).when(['der']),
            det(feminine, singular, accusative).when(['die']),
            det(feminine, plural, nominative).when(['die']),
            det(feminine, plural, genitive).when(['der']),
            det(feminine, plural, dative).when(['den']),
            det(feminine, plural, accusative).when(['die']),
            det(neuter, singular, nominative).when(['das']),
            det(neuter, singular, genitive).when(['des']),
            det(neuter, singular, dative).when(['dem']),
            det(neuter, singular, accusative).when(['das']),
            det(neuter, plural, nominative).when(['die']),
            det(neuter, plural, genitive).when(['der']),
            det(neuter, plural, dative).when(['den']),
            det(neuter, plural, accusative).when(['die']),
            det(masculine, singular, nominative).when(['ein']),
            det(masculine, singular, genitive).when(['eines']),
            det(masculine, singular, dative).when(['einem']),
            det(masculine, singular, accusative).when(['einen']),
            det(feminine, singular, nominative).when(['eine']),
            det(feminine, singular, genitive).when(['einer']),
            det(feminine, singular, dative).when(['einer']),
            det(feminine, singular, accusative).when(['eine']),
            det(_, plural, nominative).when(['einige']),
            det(_, plural, genitive).when(['einiger']),
            det(_, plural, dative).when(['einigen']),
            det(_, plural, accusative).when(['einige']),
            det(_, plural, nominative).when(['viele']),
            det(_, plural, genitive).when(['vieler']),
            det(_, plural, dative).when(['vielen']),
            det(_, plural, accusative).when(['viele']),
            det(_, plural, nominative).when(['alle']),
            det(_, plural, genitive).when(['aller']),
            det(_, plural, dative).when(['allen']),
            det(_, plural, accusative).when(['alle']),
            det(masculine, singular, nominative).when(['kein']),
            det(masculine, singular, genitive).when(['keines']),
            det(masculine, singular, dative).when(['keinem']),
            det(masculine, singular, accusative).when(['keinen']),
            det(masculine, plural, nominative).when(['keine']),
            det(masculine, plural, genitive).when(['keiner']),
            det(masculine, plural, dative).when(['keinen']),
            det(masculine, plural, accusative).when(['keine']),
            det(feminine, singular, nominative).when(['keine']),
            det(feminine, singular, genitive).when(['keiner']),
            det(feminine, singular, dative).when(['keiner']),
            det(feminine, singular, accusative).when(['keine']),
            det(feminine, plural, nominative).when(['keine']),
            det(feminine, plural, genitive).when(['keiner']),
            det(feminine, plural, dative).when(['keinen']),
            det(feminine, plural, accusative).when(['keine']),
            det(masculine, singular, nominative).when(['mancher']),
            det(masculine, singular, genitive).when(['manches']),
            det(masculine, singular, dative).when(['manchem']),
            det(masculine, singular, accusative).when(['manchen']),
            det(masculine, plural, nominative).when(['manche']),
            det(masculine, plural, genitive).when(['mancher']),
            det(masculine, plural, dative).when(['manchen']),
            det(masculine, plural, accusative).when(['manchen']),
            det(feminine, singular, nominative).when(['manche']),
            det(feminine, singular, genitive).when(['mancher']),
            det(feminine, singular, dative).when(['mancher']),
            det(feminine, singular, accusative).when(['manche']),
            det(feminine, plural, nominative).when(['manche']),
            det(feminine, plural, genitive).when(['mancher']),
            det(feminine, plural, dative).when(['manchen']),
            det(feminine, plural, accusative).when(['manche']),
            det(masculine, singular, nominative).when(['jeder']),
            det(masculine, singular, genitive).when(['jedes']),
            det(masculine, singular, dative).when(['jedem']),
            det(masculine, singular, accusative).when(['jeden']),
            det(feminine, singular, nominative).when(['jede']),
            det(feminine, singular, genitive).when(['jeder']),
            det(feminine, singular, dative).when(['jeder']),
            det(feminine, singular, accusative).when(['jede']),
            noun(masculine, singular, nominative).when(['hund']),
            noun(masculine, singular, genitive).when(['hundes']),
            noun(masculine, singular, dative).when(['hund']),
            noun(masculine, singular, accusative).when(['hund']),
            noun(masculine, plural, nominative).when(['hunde']),
            noun(masculine, plural, genitive).when(['hunde']),
            noun(masculine, plural, dative).when(['hunden']),
            noun(masculine, plural, accusative).when(['hunde']),
            noun(feminine, singular, nominative).when(['katze']),
            noun(feminine, singular, genitive).when(['katze']),
            noun(feminine, singular, dative).when(['katze']),
            noun(feminine, singular, accusative).when(['katze']),
            noun(feminine, plural, nominative).when(['katzen']),
            noun(feminine, plural, genitive).when(['katzen']),
            noun(feminine, plural, dative).when(['katzen']),
            noun(feminine, plural, accusative).when(['katzen']),
            noun(masculine, singular, nominative).when(['kater']),
            noun(masculine, singular, genitive).when(['katers']),
            noun(masculine, singular, dative).when(['kater']),
            noun(masculine, singular, accusative).when(['kater']),
            noun(masculine, plural, nominative).when(['kater']),
            noun(masculine, plural, genitive).when(['kater']),
            noun(masculine, plural, dative).when(['katern']),
            noun(masculine, plural, accusative).when(['kater']),
            noun(feminine, singular, nominative).when(['maus']),
            noun(feminine, singular, genitive).when(['maus']),
            noun(feminine, singular, dative).when(['maus']),
            noun(feminine, singular, accusative).when(['maus']),
            noun(feminine, plural, nominative).when(['maeuse']),
            noun(feminine, plural, genitive).when(['maeuse']),
            noun(feminine, plural, dative).when(['maeusen']),
            noun(feminine, plural, accusative).when(['maeuse']),
            noun(neuter, plural, nominative).when(['leute']),
            noun(neuter, plural, genitive).when(['leute']),
            noun(neuter, plural, dative).when(['leuten']),
            noun(neuter, plural, accusative).when(['leute']),
            verb(singular, nominative, Trans).when(['fehlt']),
            verb(plural, nominative, Trans).when(['fehlen']),
            verb(singular, dative, transitive).when(['fehlt']),
            verb(plural, dative, transitive).when(['fehlen']),
            verb(singular, _, intransitive).when(['schlaeft']),
            verb(plural, _, intransitive).when(['schlafen']),
            verb(singular, nominative, intransitive).when(['frisst']),
            verb(plural, nominative, intransitive).when(['fressen']),
            verb(singular, accusative, transitive).when(['frisst']),
            verb(plural, accusative, transitive).when(['fressen']),
            verb(singular, nominative, intransitive).when(['jagt']),
            verb(plural, nominative, intransitive).when(['jagen']),
            verb(singular, accusative, transitive).when(['jagt']),
            verb(plural, accusative, transitive).when(['jagen']),
            verb(singular, _, intransitive).when(['spielt']),
            verb(plural, _, intransitive).when(['spielen']),
        ),
    )

    # words = 'eine maus jagt viele katzen'.split()
    # words = 'manche maeuse jagen viele katze'.split()
    words = ['der', C, D, 'die', F]
    # words = [C, D, 'schlaeft']
    # words = ['manche', B, C]
    # words = [B, 'hund', D, E, F]
    # words = [B, 'hunde', 'jagen', C, 'katzen']
    # words = [B, C, 'jagen']
    # words = [B, C, 'jagt', D, E]

    print(f'senstences that match {words!s}:')
    print()
    for subst in db.ask(equal(words, W), phrase(s, W)):
        print(str(subst[W]))
    else:
        print('No.')


grammar(database())
